### ISSUE TITLE
KeyError: 'pop from an empy set'

### ISSUE THREAD

**Issue by absoluteblack** [nnguyen259/ReverieRandomizer#1]
```
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "app.py", line 48, in _randomize
  File "frames\masterquartz.py", line 38, in randomize
  File "randomizers\masterquartrandomizer.py", line 67, in randomize_master_quartz
KeyError: 'pop from an empty set'
```
Not sure if there's more detailed logging dumped somewhere, but here's the traceback, and a screenshot of the settings and seed.
![image](https://github.com/nnguyen259/ReverieRandomizer/assets/8021141/8ae2bedd-2df5-41c4-b7a7-c82cf64a7714)
Seems consistent across seeds and settings as long as shuffle and either Same Slot Abilities or All Abilities is checked, might just be an off by one or something?

**Comment by absoluteblack** [comment]
I think I got it - the issue is, when you take the `set` of skills to shuffle from, that removes duplicates. Which brings the total number of skills down from 168 (56 MQs with 3 skill lines each) to just 78. So then the pop runs out of options to assign.
```
print(len(skills))
if selection_mode == "shuffle":
    skills = set(skills)
print(len(skills))
```
```
168
78
```

**Comment by nnguyen259** [comment]
Thanks for catching that! It's supposed to be the other way around whoops, only apply set if the mode is not shuffle

**Comment by absoluteblack** [comment]
Ah, so on random mode, it still picks skills from the pool, just without maintaining the weighting. Or, it should, anyway. An easy fix at least!
